LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY CLOCK  IS
	PORT( CLK, EN, SW: IN STD_LOGIC;
			key : IN STD_LOGIC;
			m1, m0: OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			cout : OUT STD_LOGIC
			);
END CLOCK;

ARCHITECTURE BHV OF CLOCK IS

SIGNAL CNT0, CNT1 : STD_LOGIC_VECTOR(3 DOWNTO 0);
SIGNAL MCLK : STD_LOGIC; 

BEGIN

PROCESS(EN, SW, CLK, KEY)
BEGIN

IF SW = '0' THEN MCLK <= CLK;
ELSE MCLK <= KEY;
END IF;

IF EN = '1' THEN
	IF MCLK'EVENT AND MCLK = '1' THEN
		COUT <= '0';
		IF CNT0 = "1001" THEN
			CNT0 <= "0000";
			IF CNT1 = "0101" THEN
				CNT1 <= "0000";
				COUT <= '1';
			ELSE
				CNT1 <= CNT1 + 1;
			END IF;
		ELSE
			CNT0 <= CNT0 + 1;
		END IF;
	END IF;
END IF;

END PROCESS;

M1 <= CNT1;
M0 <= CNT0;

END BHV;
