LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY CLOCK_H  IS
	PORT( CLK, EN, SW: IN STD_LOGIC;
			key : IN STD_LOGIC;
			h1, h0: OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			cout : OUT STD_LOGIC
			);
END CLOCK_H;

ARCHITECTURE BHV OF CLOCK_H IS

SIGNAL CNT0 : STD_LOGIC_VECTOR(3 DOWNTO 0) := "0010";
SIGNAL CNT1 : STD_LOGIC_VECTOR(3 DOWNTO 0) := "0010";
SIGNAL MCLK : STD_LOGIC; 

BEGIN

PROCESS(EN, SW, CLK, KEY, MCLK)
BEGIN

IF SW = '0' THEN MCLK <= CLK;
ELSE MCLK <= KEY;
END IF;

IF EN = '1' THEN
	IF MCLK'EVENT AND MCLK = '1' THEN
		COUT <= '0';
		IF CNT0 = "0011" AND CNT1 = "0010" THEN
			CNT0 <= "0000";
			CNT1 <= "0000";
			COUT <= '1';
		ELSIF CNT0 = "1001" THEN
			CNT0 <= "0000";
			CNT1 <= CNT1 + 1;
		ELSE
			CNT0 <= CNT0 + 1;
		END IF;
	END IF;
END IF;

END PROCESS;

h1 <= CNT1;
h0 <= CNT0;

END BHV;
