LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY FD2 IS
	PORT( CLK, EN : IN STD_LOGIC;
			CLK_1: OUT STD_LOGIC
			);
END FD2;

ARCHITECTURE BHV OF FD2 IS
	SIGNAL Q1 : STD_LOGIC ;
BEGIN
PROCESS(CLK, EN, Q1)
	VARIABLE TEMP1 : INTEGER RANGE 0 TO 9;
BEGIN
IF EN = '1' THEN
IF CLK'EVENT AND CLK = '1' THEN
	IF TEMP1 < 8 THEN
		TEMP1 := TEMP1 + 1;
		Q1 <= '0';
	ELSIF TEMP1 < 9 THEN
		TEMP1 := TEMP1 + 1;
		Q1 <= '1';
	ELSE
		TEMP1 := 0;
		Q1 <= '1';
	END IF;
END IF;
ELSE
	Q1 <= '0';
END IF;
CLK_1 <= Q1;
END PROCESS;

END BHV;