LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY FD3 IS
	PORT( CLK : IN STD_LOGIC;
			CLK_1: OUT STD_LOGIC
			);
END FD3;

ARCHITECTURE BHV OF FD3 IS
	SIGNAL Q1 : STD_LOGIC ;
BEGIN
PROCESS(CLK)
	VARIABLE TEMP1 : INTEGER RANGE 0 TO 5;
BEGIN
IF CLK'EVENT AND CLK = '1' THEN
	IF TEMP1 < 3 THEN
		TEMP1 := TEMP1 + 1;
		Q1 <= '0';
	ELSIF TEMP1 < 5 THEN
		TEMP1 := TEMP1 + 1;
		Q1 <= '1';
	ELSE
		TEMP1 := 0;
		Q1 <= '1';
	END IF;
END IF;

CLK_1 <= Q1;
END PROCESS;

END BHV;