LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY FD IS
	PORT( CLK, EN: IN STD_LOGIC;
			CLK_1: OUT STD_LOGIC
			);
END FD;

ARCHITECTURE BHV OF FD IS
	SIGNAL Q1 : STD_LOGIC ;
BEGIN
PROCESS(CLK, Q1)
	VARIABLE TEMP1 : INTEGER RANGE 0 TO 4999999;
BEGIN
IF EN = '1' THEN
IF CLK'EVENT AND CLK = '1' THEN
	IF TEMP1 < 2499999 THEN
		TEMP1 := TEMP1 + 1;
		Q1 <= '0';
	ELSIF TEMP1 < 4999999 THEN
		TEMP1 := TEMP1 + 1;
		Q1 <= '1';
	ELSE
		TEMP1 := 0;
		Q1 <= '1';
	END IF;
END IF;
ELSE
	Q1 <= '0';
END IF;

CLK_1 <= Q1;
END PROCESS;

END BHV;