LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY SUM  IS
	PORT( LOAD, RSET: IN STD_LOGIC;
			DATA : IN INTEGER RANGE 0 TO 9999;
			
			RES: OUT STD_LOGIC_VECTOR(11 DOWNTO 0)
			);
END SUM;

ARCHITECTURE BHV OF SUM IS
SIGNAL CNT : INTEGER RANGE 0 TO 9999 := 0;

BEGIN
PROCESS(LOAD, RSET, DATA)
BEGIN

IF RSET = '1' THEN
	CNT <= 0;
ELSIF LOAD'EVENT AND LOAD = '1' THEN
	CNT <= CNT + DATA;
END IF;

END PROCESS;


END BHV;
