LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY SUM  IS
	PORT( LOAD, RSET: IN STD_LOGIC;
			DATA : IN STD_LOGIC_VECTOR(13 DOWNTO 0);
			
			RES0, RES1, RES2, RES3 : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
			);
END SUM;

ARCHITECTURE BHV OF COUNT IS
SIGNAL CNT : INTEGER RANGE 0 TO 9999 := 0;

BEGIN
PROCESS(EN, CLK)
BEGIN

IF RSET = '1' THEN
	CNT <= 0;
ELSIF LOAD'EVENT AND LOAD = '1' THEN
	
END IF;

END PROCESS;


END BHV;
